/*
PAGE: LicenseRecordDetailsPage.cs
ROLE: Dealer Admin / Support
PURPOSE:
  Display detailed read-only view of a single license record. Show company, product, license metadata, modules list, and checksum verification.
  Allow navigation back to LicenseRecordsPage.
*/

using System;
using System.Drawing;
using System.Linq;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraGrid.Views.Grid;
using Autosoft_Licensing.Services;
using Autosoft_Licensing.Models;
using Autosoft_Licensing.Utils;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Autosoft_Licensing.UI.Pages
{
    public partial class LicenseRecordDetailsPage : PageBase
    {
        private ILicenseDatabaseService _dbService;
        private IProductService _productService;
        private IEncryptionService _encryptionService;
        private IFileService _fileService;

        private int _licenseId;
        private LicenseMetadata _currentLicense;

        // Navigation event
        public event EventHandler<NavigateEventArgs> NavigateRequested;

        public class NavigateEventArgs : EventArgs
        {
            public string TargetPage { get; set; }
        }

        public LicenseRecordDetailsPage()
        {
            InitializeComponent();

            try
            {
                if (!DesignMode)
                {
                    // Wire services from ServiceRegistry (best-effort)
                    try { if (_dbService == null) _dbService = ServiceRegistry.Database; } catch { }
                    try { if (_productService == null) _productService = ServiceRegistry.Product; } catch { }
                    try { if (_encryptionService == null) _encryptionService = ServiceRegistry.Encryption; } catch { }
                    try { if (_fileService == null) _fileService = ServiceRegistry.File; } catch { }

                    // Wire event handlers
                    btnBack.Click += btnBack_Click;
                    btnCopyChecksum.Click += btnCopyChecksum_Click;
                    btnVerifyChecksum.Click += btnVerifyChecksum_Click;
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"LicenseRecordDetailsPage ctor error: {ex}");
            }
        }

        /// <summary>
        /// Initialize the page with a license ID and load details.
        /// </summary>
        public void Initialize(int licenseId)
        {
            _licenseId = licenseId;
            LoadLicenseDetails();
        }

        /// <summary>
        /// Load license details from database and populate UI.
        /// </summary>
        private void LoadLicenseDetails()
        {
            try
            {
                if (_dbService == null)
                {
                    ShowError("Database service not initialized.");
                    return;
                }

                _currentLicense = _dbService.GetLicenseById(_licenseId);
                if (_currentLicense == null)
                {
                    ShowError("License record not found.");
                    return;
                }

                // Populate header fields
                txtCompanyName.Text = _currentLicense.CompanyName ?? string.Empty;
                txtProductCode.Text = _currentLicense.ProductID ?? string.Empty;

                // Get product name from ProductService
                string productName = string.Empty;
                try
                {
                    if (_productService != null)
                        productName = _productService.GetProductName(_currentLicense.ProductID) ?? string.Empty;
                }
                catch { }
                txtProductName.Text = productName;

                txtLicenseType.Text = _currentLicense.LicenseType.ToString();

                // Display dates (convert UTC to local)
                try
                {
                    dtIssueDate.DateTime = _currentLicense.ValidFromUtc.ToLocalTime();
                    dtExpiryDate.DateTime = _currentLicense.ValidToUtc.ToLocalTime();
                }
                catch
                {
                    dtIssueDate.DateTime = DateTime.Now;
                    dtExpiryDate.DateTime = DateTime.Now;
                }

                // Status: show persisted DB status, but reflect expiry visually if needed
                txtStatus.Text = _currentLicense.Status.ToString();

                // Generated By (lookup user)
                string generatedBy = "Unknown";
                try
                {
                    if (_currentLicense.ImportedByUserId.HasValue && ServiceRegistry.User != null)
                    {
                        var user = ServiceRegistry.User.GetUserById(_currentLicense.ImportedByUserId.Value);
                        if (user != null)
                            generatedBy = user.DisplayName ?? user.Username ?? "Unknown";
                    }
                }
                catch { }
                txtGeneratedBy.Text = generatedBy;

                // Currency (new binding)
                txtCurrency.Text = _currentLicense.CurrencyCode ?? string.Empty;

                // Remark (bind to stored remarks)
                memRemark.Text = _currentLicense.Remarks ?? string.Empty;

                // Extract and display checksum from RawAslBase64
                txtChecksum.Text = string.Empty;
                lblChecksumStatus.Text = string.Empty;
                btnVerifyChecksum.Enabled = false;

                if (!string.IsNullOrWhiteSpace(_currentLicense.RawAslBase64) && _encryptionService != null)
                {
                    try
                    {
                        // Decrypt the ASL to get the LicenseData with checksum
                        var decryptedJson = _encryptionService.DecryptAslToJson(
                            _currentLicense.RawAslBase64,
                            CryptoConstants.AesKey,
                            CryptoConstants.AesIV);

                        if (!string.IsNullOrWhiteSpace(decryptedJson))
                        {
                            var licenseData = JsonConvert.DeserializeObject<LicenseData>(decryptedJson);
                            if (licenseData != null && !string.IsNullOrWhiteSpace(licenseData.ChecksumSHA256))
                            {
                                txtChecksum.Text = licenseData.ChecksumSHA256;
                                btnVerifyChecksum.Enabled = true;
                            }
                        }
                    }
                    catch (Exception ex)
                    {
                        System.Diagnostics.Debug.WriteLine($"Failed to extract checksum: {ex}");
                        txtChecksum.Text = "(Unable to read checksum)";
                    }
                }
                else
                {
                    txtChecksum.Text = "(No ASL data available)";
                }

                // Load modules
                LoadModules();
            }
            catch (Exception ex)
            {
                ShowError("Failed to load license details.");
                System.Diagnostics.Debug.WriteLine($"LoadLicenseDetails error: {ex}");
            }
        }

        /// <summary>
        /// Load modules for the product and display in grid.
        /// </summary>
        private void LoadModules()
        {
            try
            {
                if (_currentLicense == null)
                {
                    grdModules.DataSource = null;
                    return;
                }

                var activatedModuleCodes = _currentLicense.ModuleCodes ?? new List<string>();
                if (!activatedModuleCodes.Any())
                {
                    grdModules.DataSource = null;
                    return;
                }

                List<object> moduleList = new List<object>();

                if (_productService != null)
                {
                    try
                    {
                        var allModules = _productService.GetModulesByProductId(_currentLicense.ProductID);

                        var activatedModules = allModules
                            .Where(m => activatedModuleCodes.Contains(m.ModuleCode, StringComparer.OrdinalIgnoreCase))
                            .Select(m => new
                            {
                                Name = string.IsNullOrWhiteSpace(m.ModuleName) ? m.ModuleCode : m.ModuleName,
                                Description = m.Description ?? string.Empty
                            })
                            .ToList();

                        if (activatedModules.Any())
                        {
                            moduleList.AddRange(activatedModules);
                        }
                        else
                        {
                            moduleList.AddRange(activatedModuleCodes.Select(code => new
                            {
                                Name = code,
                                Description = string.Empty
                            }));
                        }
                    }
                    catch (Exception ex)
                    {
                        System.Diagnostics.Debug.WriteLine($"LoadModules product service error: {ex}");
                        moduleList.AddRange(activatedModuleCodes.Select(code => new
                        {
                            Name = code,
                            Description = string.Empty
                        }));
                    }
                }
                else
                {
                    moduleList.AddRange(activatedModuleCodes.Select(code => new
                    {
                        Name = code,
                        Description = string.Empty
                    }));
                }

                grdModules.DataSource = moduleList;

                try
                {
                    viewModules.BestFitColumns();
                }
                catch { }
            }
            catch (Exception ex)
            {
                grdModules.DataSource = null;
                System.Diagnostics.Debug.WriteLine($"LoadModules error: {ex}");
            }
        }

        #region Event Handlers

        private void btnBack_Click(object sender, EventArgs e)
        {
            try
            {
                // Trigger navigation back to LicenseRecordsPage
                NavigateRequested?.Invoke(this, new NavigateEventArgs
                {
                    TargetPage = "LicenseRecordsPage"
                });
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"btnBack_Click error: {ex}");
                ShowError("Failed to navigate back.");
            }
        }

        private void btnCopyChecksum_Click(object sender, EventArgs e)
        {
            try
            {
                var checksum = txtChecksum.Text ?? string.Empty;
                if (string.IsNullOrWhiteSpace(checksum))
                {
                    ShowError("No checksum available to copy.");
                    return;
                }

                Clipboard.SetText(checksum);
                ShowInfo("Checksum copied.", "Success");
            }
            catch (Exception ex)
            {
                ShowError("Failed to copy checksum.");
                System.Diagnostics.Debug.WriteLine($"btnCopyChecksum_Click error: {ex}");
            }
        }

        private void btnVerifyChecksum_Click(object sender, EventArgs e)
        {
            try
            {
                // Validate prerequisites
                if (_currentLicense == null)
                {
                    ShowError("No license record loaded.");
                    return;
                }

                var storedChecksum = txtChecksum.Text?.Trim();
                if (string.IsNullOrWhiteSpace(storedChecksum) || storedChecksum.StartsWith("("))
                {
                    ShowError("No valid checksum available to verify.");
                    return;
                }

                if (string.IsNullOrWhiteSpace(_currentLicense.RawAslBase64))
                {
                    ShowError("Raw ASL data not available for verification.");
                    return;
                }

                if (_encryptionService == null)
                {
                    ShowError("Encryption service not initialized.");
                    return;
                }

                // Step 1: Decrypt the ASL to get the full JSON
                string decryptedJson;
                try
                {
                    decryptedJson = _encryptionService.DecryptAslToJson(
                        _currentLicense.RawAslBase64,
                        CryptoConstants.AesKey,
                        CryptoConstants.AesIV);
                }
                catch (Exception ex)
                {
                    ShowError($"Failed to decrypt license file: {ex.Message}");
                    System.Diagnostics.Debug.WriteLine($"Decryption error: {ex}");
                    return;
                }

                if (string.IsNullOrWhiteSpace(decryptedJson))
                {
                    ShowError("Decrypted data is empty.");
                    return;
                }

                // Step 2: Parse JSON and remove the ChecksumSHA256 field
                JObject jsonObj;
                try
                {
                    jsonObj = JObject.Parse(decryptedJson);
                }
                catch (Exception ex)
                {
                    ShowError($"Failed to parse license JSON: {ex.Message}");
                    System.Diagnostics.Debug.WriteLine($"JSON parse error: {ex}");
                    return;
                }

                // Remove the checksum field before canonicalization
                jsonObj.Remove("ChecksumSHA256");

                // Step 3: Canonicalize the JSON (sorted keys, compact)
                byte[] canonicalBytes;
                try
                {
                    canonicalBytes = CanonicalJsonSerializer.SerializeToUtf8Bytes(jsonObj);
                }
                catch (Exception ex)
                {
                    ShowError($"Failed to canonicalize JSON: {ex.Message}");
                    System.Diagnostics.Debug.WriteLine($"Canonicalization error: {ex}");
                    return;
                }

                // Step 4: Compute SHA-256 checksum
                string computedChecksum;
                try
                {
                    computedChecksum = ChecksumHelper.ComputeSha256HexLower(canonicalBytes);
                }
                catch (Exception ex)
                {
                    ShowError($"Failed to compute checksum: {ex.Message}");
                    System.Diagnostics.Debug.WriteLine($"Checksum computation error: {ex}");
                    return;
                }

                // Step 5: Compare checksums (case-insensitive)
                bool isValid = string.Equals(
                    computedChecksum,
                    storedChecksum,
                    StringComparison.OrdinalIgnoreCase);

                // Update UI based on result
                if (isValid)
                {
                    lblChecksumStatus.Text = "✓ Valid";
                    lblChecksumStatus.Appearance.ForeColor = Color.Green;
                    ShowInfo("Checksum verification passed. License file is authentic and has not been tampered with.", "Valid");
                }
                else
                {
                    lblChecksumStatus.Text = "✗ Invalid";
                    lblChecksumStatus.Appearance.ForeColor = Color.Red;

                    // Updated: show detailed mismatch information to the admin
                    ShowError($"Checksum Mismatch!\n\nStored in JSON: {storedChecksum}\nRe-computed: {computedChecksum}\n\nThis indicates the DB record differs from the original payload.");

                    System.Diagnostics.Debug.WriteLine($"Checksum mismatch:\nStored:   {storedChecksum}\nComputed: {computedChecksum}");
                }
            }
            catch (Exception ex)
            {
                lblChecksumStatus.Text = "✗ Error";
                lblChecksumStatus.Appearance.ForeColor = Color.Red;
                ShowError($"Checksum verification failed: {ex.Message}");
                System.Diagnostics.Debug.WriteLine($"btnVerifyChecksum_Click error: {ex}");
            }
        }

        #endregion
    }
}